kind: GenericOperatorConfig
apiVersion: operator.openshift.io/v1alpha1
leaderElection:
  disable: true
interval: "30s"
storagePath: /tmp/insights-operator
endpoint: https://localhost:8080
#impersonate: system:serviceaccount:openshift-insights:gather
